### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by frcroth** [hpi-swa-teaching/RichTextEditing#92]
Structures not being applied

**Comment by frcroth** [comment]
@sirkrypt0 @oleschl @j-hellenberg Failing intentionally? What was the consesus on this? Change tests?

**Comment by oleschl** [comment]
I went ahead and removed the test for the moment that had unexpected behavior. However if the customer wants this behavior we should add it again. Also kinda "fixed" the remaining failing tests. They failed because of the bug discussed on Monday that a dot ('.') is not a special character and thus structures are not applied to it.

**Comment by oleschl** [comment]
dev is now green except coverage
